version: "3.9" # docker-compose version
   
services:
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - ./postgres:/data/postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5000:5432"
    networks:
      - postgres
    restart: unless-stopped
    
networks:
    postgres:
        driver: bridge

volumes:
  postgres:
