# Generated by Django 3.2.4 on 2021-07-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_modelx'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modelx',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
